#!/bin/bash

# Define the name of the Conda environment
echo "This will ONLY WORK ON PYTHON 3.10"
python -m venv venv
source venv/bin/activate

pip install --upgrade pip setuptools wheel

pip install -e . --no-cache-dir

echo "---"
echo "Done. Please run 'conda activate $conda_env_name' to activate the Conda environment before running any scripts."
echo "---"