seed: 1234

trainer:
  gpus: [4]
  # accelerator: "gpu"
  overfit_batches: 0.0
  check_val_every_n_epoch: 2
  fast_dev_run: False
  max_epochs: 100
  min_epochs: 1
  num_sanity_val_steps: 0
  auto_lr_find: False
  checkpoint_callback: True

callbacks:
  model_checkpoint:
    save_top_k: 1
    save_weights_only: True
    mode: "min"
    monitor: "val/loss"
    filename: "{epoch}-{val/loss:.2f}-{val/cer:.2f}"
  early_stopping:
    patience: 3
    mode: "min"
    monitor: "val/loss"
    min_delta: 0.001

data:
  batch_size: 32
  num_workers: 16
  pin_memory: false
  max_output_len: 350

lit_model:
  # Optimizer
  lr: 0.001
  weight_decay: 0.0001
  # Scheduler
  milestones: [10]
  gamma: 0.5
  # Model
  d_model: 128
  dim_feedforward: 256
  nhead: 4
  dropout: 0.3
  num_decoder_layers: 3
  max_output_len: 350

logger:
  project: "image-to-latex"
  log_model: "all"
